CREATE TABLE COOK_USER(
USER_ID VARCHAR2(40),
USER_PW VARCHAR2(40),
USER_EMAIL VARCHAR2(40),
USER_SDATE DATE
);

CREATE TABLE USER_P(
USER_ID VARCHAR2(40),
USER_NICK VARCHAR2(40),
USER_IMG VARCHAR2(50),
USER_INFO CLOB
);

CREATE TABLE COOK(
COOK_ID NUMBER(20),
COOK_TITLE VARCHAR2(40),
USER_ID VARCHAR2(40),
COOK_POTO VARCHAR2(50),
COOK_INFO CLOB,
COOK_DATE DATE
);

CREATE TABLE COOK_INFO(
COOK_ID NUMBER(20),
COOK_INFO_NUM NUMBER(20),
COOK_CONTENT CLOB,
COOK_IMG VARCHAR2(50)
);

CREATE TABLE COOK_VIEWR(
COOK_ID NUMBER(20),
COOK_VIEW NUMBER(30),
COOK_GOOD NUMBER(30)
);

CREATE TABLE COOK_GUEST(
COOK_ID NUMBER(20),
USER_ID VARCHAR2(40),
RP_ID NUMBER(20),
GUEST_CONTENT CLOB,
GUEST_DATE DATE
);

CREATE TABLE COOK_QA(
QA_ID NUMBER(20),
QA_TITLE VARCHAR2(50),
QA_CONTENT CLOB,
QA_DATE DATE
);

CREATE TABLE COOK_STAR(
COOK_ID NUMBER(20),
USER_ID VARCHAR2(40)
);


insert into cook_user values('mas09', '1111','song@gmail.com', sysdate);
insert into user_p values('mas09', '관리자 계정', 'img.jpg', '관리자용 계정입니다.');